session_name: blog
start_directory: ./
windows:
- focus: 'true'
  layout: main-vertical
  panes:
  - jekyll serve
  - shell_command:
    - git status
    - gem outdated | grep github-pages
  window_name: tmuxp
